import { HFTStrategyConfig } from '../hft/types';

export const hftStrategies: HFTStrategyConfig[] = [
  {
    name: 'EUR/USD Market Making',
    type: 'market_making',
    timeframe: '1s',
    parameters: {
      entryThreshold: 0.0002,
      exitThreshold: 0.0001,
      stopLoss: 0.0005,
      takeProfit: 0.0003,
      maxPositions: 10,
      maxDrawdown: 0.02,
      riskPerTrade: 0.001,
      minVolume: 100000,
      maxSpread: 0.0003,
      minImbalance: 0.6,
      correlationThreshold: 0.7,
      lookbackPeriod: 100,
      volatilityWindow: 20,
      momentumPeriod: 10,
      meanReversionStrength: 2,
      inventoryLimits: {
        max: 1000000,
        min: -1000000,
      },
    },
    riskManagement: {
      maxLeverage: 10,
      maxRiskPerTrade: 0.02,
      maxDailyLoss: 0.05,
      maxPositionSize: 1000000,
      emergencyCloseThreshold: 0.1,
    },
    execution: {
      orderTypes: ['limit', 'ioc'],
      timeInForce: ['ioc', 'fok'],
      minOrderInterval: 100,
      maxOrdersPerSecond: 50,
      smartOrderRouting: true,
      adaptiveOrderSizing: true,
    },
  },
  {
    name: 'GBP/USD Order Flow',
    type: 'orderflow_imbalance',
    timeframe: '1s',
    parameters: {
      entryThreshold: 0.7,
      exitThreshold: 0.3,
      stopLoss: 0.0008,
      takeProfit: 0.0015,
      maxPositions: 5,
      maxDrawdown: 0.015,
      riskPerTrade: 0.002,
      minVolume: 50000,
      maxSpread: 0.0004,
      minImbalance: 0.7,
      correlationThreshold: 0.6,
      lookbackPeriod: 50,
      volatilityWindow: 30,
      momentumPeriod: 5,
      meanReversionStrength: 1.5,
      inventoryLimits: {
        max: 500000,
        min: -500000,
      },
    },
    riskManagement: {
      maxLeverage: 5,
      maxRiskPerTrade: 0.015,
      maxDailyLoss: 0.04,
      maxPositionSize: 500000,
      emergencyCloseThreshold: 0.08,
    },
    execution: {
      orderTypes: ['market', 'ioc'],
      timeInForce: ['ioc'],
      minOrderInterval: 50,
      maxOrdersPerSecond: 100,
      smartOrderRouting: true,
      adaptiveOrderSizing: true,
    },
  },
  {
    name: 'USD/JPY Mean Reversion',
    type: 'price_reversion',
    timeframe: '5s',
    parameters: {
      entryThreshold: 2.0,
      exitThreshold: 0.5,
      stopLoss: 0.001,
      takeProfit: 0.002,
      maxPositions: 3,
      maxDrawdown: 0.02,
      riskPerTrade: 0.001,
      minVolume: 75000,
      maxSpread: 0.0005,
      minImbalance: 0.5,
      correlationThreshold: 0.8,
      lookbackPeriod: 200,
      volatilityWindow: 50,
      momentumPeriod: 20,
      meanReversionStrength: 3,
      inventoryLimits: {
        max: 750000,
        min: -750000,
      },
    },
    riskManagement: {
      maxLeverage: 8,
      maxRiskPerTrade: 0.018,
      maxDailyLoss: 0.045,
      maxPositionSize: 750000,
      emergencyCloseThreshold: 0.09,
    },
    execution: {
      orderTypes: ['limit', 'market'],
      timeInForce: ['gtc', 'ioc'],
      minOrderInterval: 200,
      maxOrdersPerSecond: 30,
      smartOrderRouting: true,
      adaptiveOrderSizing: true,
    },
  },
];

export default hftStrategies;
